# 多维数组的运算
通过数组的多维运算可以高效的实现神经网络

## 3.3.1 多维数组

In [4]:
# 一维数组
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)
A.shape

[1 2 3 4]


(4,)

In [3]:
np.ndim(A)  # 获取数组的维度

1

In [5]:
# 二维数组
B = np.array([[1, 2],[3, 4],[5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
np.ndim(B)

2

In [7]:
B.shape

(3, 2)

## 3.3.2 矩阵乘法

**2×2矩阵与2×2矩阵相乘**

In [15]:
C = np.array([[1,2],[3,4]])
C.shape  # (2, 2)
D = np.array([[5,6],[7,8]])
D.shape  # (2, 2)
np.dot(C, D)

array([[19, 22],
       [43, 50]])

In [16]:
np.dot(D, C)

array([[23, 34],
       [31, 46]])

**注意：** np.dot(C, D)和np.dot(D, C)的结果可能是不一样的，在使用时需要额外注意

**2×3矩阵与3×2矩阵相乘**

In [17]:
E = np.array([[1,2,3],[4,5,6]])
E.shape

(2, 3)

In [18]:
F = np.array([[1,2],[3,4],[5,6]])
F.shape

(3, 2)

In [19]:
np.dot(E, F)

array([[22, 28],
       [49, 64]])

**矩阵A，B， 当且仅当A的列数 = B的行数时，A和B才能相乘**

In [20]:
G = np.array([[1,2],[3,4]])
G.shape

(2, 2)

In [22]:
np.dot(E, G)  # 2×3矩阵和2×2矩阵相乘会报错

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## 3.3.3 神经网络的内积
使用Numpy的矩阵来实现神经网络。该神经网络只有权重，省略了偏置和激活函数

In [25]:
# 定义输入
X = np.array([1,2])
X.shape

(2,)

In [27]:
W = np.array([[1,3,5],[2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [28]:
W.shape

(2, 3)

In [30]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
